### ISSUE TITLE
[Client] Failed SSL Certificate Configuration in NanoMQ when using Docker

### ISSUE THREAD

**Issue by dinhthanhhai2012** [nanomq/nanomq#1577]
**Describe the bug**
Config ssl on Linux (using Docker compose) is not log anything, connect by only username & password is succesful, but when connect to that broker by MQTTX, it error.

**Expected behavior**

**To Reproduce**
config nanomq in docker-compose.yml

```
   nanomq-dev:
     image: emqx/nanomq:0.14.1-full
     container_name: nanomq-dev
     volumes:
       - ../nanomq-certs/ca_certificate.pem:/etc/certs/ca_certificate.pem:ro
       - ../nanomq-certs/server_certificate.pem:/etc/certs/server_certificate.pem:ro
       - ../nanomq-certs/private_key.pem:/etc/certs/private_key.pem:ro
     environment:
       NANOMQ_TLS_ENABLE: 'true'
       NANOMQ_TLS_CA_CERT_PATH: '/etc/certs/ca_certificate.pem'
       NANOMQ_TLS_CERT_PATH: '/etc/certs/server_certificate.pem'
       NANOMQ_TLS_KEY_PATH: '/etc/certs/private_key.pem'
       NANOMQ_TLS_VERIFY_PEER: 'true'
       NANOMQ_TLS_FAIL_IF_NO_PEER_CERT: 'true'
     restart: always
     ports:
       - '1883:1883'
       - '8083:8083'
       - '8883:8883'
```
error when connect with MQTTX with SSL:

> Error: error:0b000074:X.509 certificate routines:OPENSSL_internal:KEY_VALUES_MISMATCH
