### ISSUE TITLE
Data Bridge unable to create subscriptions

### ISSUE THREAD

**Issue by prima-ram** [nanomq/nanomq#1960]
**Describe the bug**  
I have set up a Data Bridge between a NanoMQ instance and an EMQX instance. The forwarding rule works correctly, and messages are relayed from NanoMQ to EMQX as expected. However, the subscription rules do not work correctly. NanoMQ logs indicate that the subscription to the remote topics (`cmd/topic1` and `cmd/topic2`) is established:

```bash
2024-12-14 14:22:58 [11] INFO /nanomq/nanomq/bridge.c:1060 bridge_tcp_connect_cb: Bridge client subscribed topic cmd/topic1 (qos 1 rap 0 rh 0).
```

However, when inspecting the subscriptions on the EMQX broker, the NanoMQ bridge does not appear as a subscriber.  

Interestingly, when I use the same client ID and credentials in Node-RED and manually create the subscriptions, NanoMQ begins to relay messages correctly. It seems that while everything appears configured correctly, NanoMQ does not actually create the subscription on EMQX.

---

**Expected Behavior**  
NanoMQ should successfully subscribe to the configured remote topics on EMQX and relay incoming messages to the local NanoMQ topics as defined in the `subscription` rules.

---

**Actual Behavior**  
NanoMQ reports successful subscriptions in its logs but does not actually create them on EMQX. As a result, no messages are relayed from EMQX to NanoMQ until the same client credentials and subscriptions are created manually in Node-RED or another MQTT client.

---

**To Reproduce**  
1. Configure NanoMQ with the following bridge settings:
   ```toml
   bridges.mqtt.emqx {
       server = "tls+mqtt-tcp://xxxxx.com:8883"
       proto_ver = 5
       clientid = "bridge_client"
       username = "example"
       password = "example"
       clean_start = false
       keepalive = "60s"
       ssl {
           cacertfile = "/etc/cacert.pem"
       }
       subscription = [
           {
               remote_topic = "cmd/topic1"
               local_topic = "topic3"
               qos = 1
               retain = 2
               suffix = "/emqx"
           },
           {
               remote_topic = "cmd/topic2"
               local_topic = "topic4"
               qos = 2
           }
       ]
       forwards = [
           {
               remote_topic = ""
               local_topic = "local"
               qos = 2
               prefix = "company/gateway/"
           }
       ]
   }
   ```
2. Start NanoMQ and ensure it connects to the EMQX broker.
3. Publish messages to `cmd/topic1` or `cmd/topic2` on EMQX.
4. Observe that no messages are relayed to the local NanoMQ topics (`topic3`, `topic4`).
5. Use Node-RED to connect to EMQX with the same credentials:
   - Client ID: `bridge_client`
   - Username: `example`
   - Password: `example`
   - Subscribe to `cmd/topic1` or `cmd/topic2`.
6. Publish messages to `cmd/topic1` or `cmd/topic2` on EMQX again.
7. Observe that NanoMQ now begins relaying messages correctly.

---

**Environment Details**

- **NanoMQ Version**: 0.23.1-slim
- **Operating System and Version**: Docker

---
