### ISSUE TITLE
NanoMQ 0.23.3-0.23.8 Docker ver booting issue

### ISSUE THREAD

**Issue by ppat** [nanomq/nanomq#2049]
**Describe the bug**
- NanoMQ 0.23.8-slim crashes immediately on startup with exit code 139 (SIGSEGV). 
- The same configuration works fine with 0.23.2-slim.
- This is a segmentation fault regression between 0.23.2 and 0.23.8.
- Tested with emqx/nanomq:0.23.8 (full image/non-slim variant): Same crash

**Expected behavior**
- NanoMQ should start successfully and accept MQTT connections (works with 0.23.2-slim).

**Actual Behavior**
- Container crashes immediately with exit code 139 (segmentation fault). No logs are produced.

**Workaround**
- Downgrading to emqx/nanomq:0.23.2-slim works with the same configuration.

**To Reproduce**

Save the following files and run `docker compose up`:

docker-compose.yml:
```
yamlversion: '3.8'
services:
  nanomq:
    image: emqx/nanomq:0.23.8-slim
    ports:
      - "1883:1883"
      - "8081:8081" 
      - "8083:8083"
    environment:
      - NANOMQ_CONF_PATH=/etc/nanomq.conf
      - NANOMQ_HTTP_SERVER_ENABLE=true
      - NANOMQ_HTTP_SERVER_PORT=8081
      - NANOMQ_HTTP_SERVER_USERNAME=admin
      - NANOMQ_HTTP_SERVER_PASSWORD=testpassword123
    volumes:
      - ./nanomq.conf:/etc/nanomq.conf:ro
      - ./nanomq_acl.conf:/etc/nanomq_acl.conf:ro
      - ./nanomq_pwd.conf:/etc/nanomq_pwd.conf:ro
    restart: unless-stopped
```

nanomq.conf:
```
auth {
  allow_anonymous = false
  no_match = deny
  deny_action = disconnect
  password = {include "/etc/nanomq_pwd.conf"}
  acl = {include "/etc/nanomq_acl.conf"}
}
```

nanomq_acl.conf:
```
rules = [
  {"permit": "allow", "username": "admin"}
  {"permit": "allow", "username": "app"}
]
```

nanomq_pwd.conf:
```
"admin": "testpassword123"
"app": "testpassword123"
```

**Environment Details**
- Artifact:  DockerImage(`emqx/nanomq:0.23.8-slim@sha256:a4770d3acc9b668b2637ff3477d8280bbd9c7300d16832b897e05554582f94e8`)
- Platform: `Kubernetes` / `Docker`
- Crash: `Exit code 139 (segmentation fault)`
- Last working version: `emqx/nanomq:0.23.2-slim`
- Operating system and version
   - First encountered on Kubernetes (`v1.32.5`) running on Ubuntu (`24.04.2 LTS`) with kernel (`6.11.0-26-generic`) on `amd64` architecture
   - Then reproduced on Docker running on MacOS (`Ventura 13.4`) on `arm64` architecture

**Client SDK**
- N/A. NanoMQ fails to start up so the problem occurs before any clients can even connect. 

**Additional context**
- None
